### ISSUE TITLE
Add build file for Github Action

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#10]
> [!IMPORTANT]
> Read issue #2 first

Create a file named `build.yml` in the path: `.github/workflows/`

The content of the file is as follows:

```yaml
name: Build Push/PR - Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile with Maven
        run: mvn -B compile --file pom.xml

      - name: Test
        run: mvn -B test --file pom.xml
```

**Comment by nmarulo** [comment]
@Unagi-zoso It's all yours 👍

**Comment by Unagi-zoso** [comment]
thank you :)

**Comment by Unagi-zoso** [comment]
Hello? @nmarulo 
I encountered an error while adding a build.yml file to project. The error message is as follows:

<br>

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project despensa-rest-api: Fatal error compiling: error: release version 21 not supported -> [Help 1]
```

I believe this issue is due to a mismatch in JDK versions. Currently, the yml file specifies JDK version 17, while the pom.xml file is set to use JDK version 21.

<br>

Here are the relevant sections:

**Current build.yml JDK version**
```
- name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
```

<br>

**Current pom.xml JDK version**
```
<properties>
    <java.version>21</java.version>
    <springdoc-openapi-starter-webmvc-ui.version>2.6.0</springdoc-openapi-starter-webmvc-ui.version>
    <jacoco-maven-plugin.version>0.8.12</jacoco-maven-plugin.version>
</properties>
```

<br>

To resolve this, I propose updating the yml file to use JDK 21. Here's the proposed change:
```
// .github/workflows/build.yml

name: Build Push/PR - Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile with Maven
        run: mvn -B compile --file pom.xml

      - name: Test
        run: mvn -B test --file pom.xml
```
